-- migrate:up

CREATE TABLE mentors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(6) NOT NULL,
  full_name VARCHAR(100) NOT NULL,
  charge VARCHAR(60) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  image_url VARCHAR(100),
  linkedln_url VARCHAR(70),
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down

DROP TABLE mentors;