-- migrate:up

CREATE TABLE students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  full_name VARCHAR(100) NOT NULL,
  google_id VARCHAR(60) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  image_url VARCHAR(100),
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down

DROP TABLE students;