-- migrate:up

INSERT INTO news_items (id, title, subtitle, content, image_url, url, published) VALUES
  (1, 'Cómo ganar amigos e influir en las personas', 'Técnicas de networking profesional', 'Irán ha sustituido los sistemas de defensa antiaérea que resultaron dañados durante los ataques lanzados por Israel el mes pasado, informó Mahmoud Mousavi, subcomandante de operaciones del Ejército regular iraní, en una entrevista con Defapress publicada este domingo.

**"El enemigo sionista trató de destruir las capacidades de defensa de Irán, y algunos de nuestros sistemas de defensa resultaron dañados en esta guerra, pero con los esfuerzos de mis camaradas, los sistemas dañados fueron reemplazados y desplegados en lugares predeterminados", declaró Mousavi.**

![](https://mf.b37mrtl.ru/actualidad/public_images/2025.07/article/687cd6c359bf5b7a12787f91.jpg)

"Pudimos cubrir el espacio aéreo del país y garantizar la seguridad del querido espacio aéreo de Irán utilizando los sistemas existentes y sustituyéndolos por otros nuevos, por lo tanto, el enemigo no pudo lograr sus objetivos a pesar de sus desesperados esfuerzos", explicó.', 'uploads/news-items/default.jpg', '1-como-ganar-amigos-e-influir-en-las-personas', '2025-01-05'),
  (2, 'El poder del hábito', 'Cómo construir rutinas productivas', 'Irán ha sustituido los sistemas de defensa antiaérea que resultaron dañados durante los ataques lanzados por Israel el mes pasado, informó Mahmoud Mousavi, subcomandante de operaciones del Ejército regular iraní, en una entrevista con Defapress publicada este domingo.

**"El enemigo sionista trató de destruir las capacidades de defensa de Irán, y algunos de nuestros sistemas de defensa resultaron dañados en esta guerra, pero con los esfuerzos de mis camaradas, los sistemas dañados fueron reemplazados y desplegados en lugares predeterminados", declaró Mousavi.**

![](https://mf.b37mrtl.ru/actualidad/public_images/2025.07/article/687cd6c359bf5b7a12787f91.jpg)

"Pudimos cubrir el espacio aéreo del país y garantizar la seguridad del querido espacio aéreo de Irán utilizando los sistemas existentes y sustituyéndolos por otros nuevos, por lo tanto, el enemigo no pudo lograr sus objetivos a pesar de sus desesperados esfuerzos", explicó.

<iframe width="1991" height="888" src="https://www.youtube.com/embed/qfbDDkAE3uM" title="Los SINSENTIDOS de la saga RESIDENT EVIL (Películas) - Cómo no adaptar videojuegos - Análisis -" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>', 'uploads/news-items/default.jpg', '2-el-poder-del-habito', '2025-01-12'),
  (3, 'La psicología de la persuasión', 'Influencia y negociación', '# La psicología de la persuasión\n\n## Técnicas de persuasión\n\n1. Prueba social\n2. Autoridad\n3. Escasez', 'uploads/news-items/default.jpg', '3-la-psicologia-de-la-persuasion', '2025-01-20'),
  (4, 'El secreto de las personas altamente efectivas', 'Gestión del tiempo y enfoque', '# El secreto de las personas altamente efectivas\n\n## Principios clave\n\n- Importante vs urgente\n- Priorización\n- Productividad', 'uploads/news-items/default.jpg', '4-el-secreto-de-las-personas-altamente-efectivas', '2025-01-28'),
  (5, 'Hábitos de vida saludable', 'Bienestar físico y mental', '# Hábitos de vida saludable\n\n## Alimentación\n## Ejercicio\n## Descanso', 'uploads/news-items/default.jpg', '5-habitos-de-vida-saludable', '2025-02-03'),
  (6, 'Cómo mejorar tu productividad', 'Técnicas probadas', '# Cómo mejorar tu productividad\n\n## Técnicas\n\n- Pomodoro\n- Time blocking\n- Elimina distracciones', 'uploads/news-items/default.jpg', '6-como-mejorar-tu-productividad', '2025-02-10'),
  (7, 'Liderazgo sin cargo', 'Influye desde cualquier posición', '# Liderazgo sin cargo\n\n## Liderazgo informal\n\n- Influencia\n- Comunicación\n- Empatía', 'uploads/news-items/default.jpg', '7-liderazgo-sin-cargo', '2025-02-18'),
  (8, 'Empatía y comunicación efectiva', 'Claves para conectar con otros', '# Empatía y comunicación efectiva\n\n## Técnicas de escucha activa\n\n- Reflejar emociones\n- Validación\n- Feedback', 'uploads/news-items/default.jpg', '8-empathy-y-comunicacion-efectiva', '2025-02-25'),
  (9, 'Cómo construir una marca personal', 'Proyecta tu identidad profesional', '# Cómo construir una marca personal\n\n## Pasos clave\n\n1. Define tu propósito\n2. Crea contenido\n3. Sé coherente', 'uploads/news-items/default.jpg', '9-como-construir-una-marca-personal', '2025-03-02'),
  (10, 'Inteligencia emocional en el trabajo', 'Gestiona tus emociones y las de otros', '# Inteligencia emocional en el trabajo\n\n## Autoconocimiento\n## Automotivación\n## Habilidades interpersonales', 'uploads/news-items/default.jpg', '10-inteligencia-emocional-en-el-trabajo', '2025-03-08'),
  (11, 'Cómo escribir un currículum ganador', 'Claves para destacar en el mercado laboral', '# Cómo escribir un currículum ganador\n\n## Estructura\n## Habilidades clave\n## Experiencia relevante', 'uploads/news-items/default.jpg', '11-como-escribir-un-curriculum-ganador', '2025-03-15'),
  (12, 'Prepárate para una entrevista exitosa', 'Tips para destacar en tu próxima entrevista', '# Prepárate para una entrevista exitosa\n\n## Investigación previa\n## Preguntas comunes\n## Presentación', 'uploads/news-items/default.jpg', '12-preparate-para-una-entrevista-exitosa', '2025-03-22'),
  (13, 'Redes de contactos efectivas', 'Construye relaciones profesionales duraderas', '# Redes de contactos efectivas\n\n## Conecta con personas clave\n## Sigue las reglas de networking\n## Sé auténtico', 'uploads/news-items/default.jpg', '13-redes-de-contactos-efectivas', '2025-03-30'),
  (14, 'Cómo usar LinkedIn de forma efectiva', 'Optimiza tu perfil y tus conexiones', '# Cómo usar LinkedIn de forma efectiva\n\n## Perfil profesional\n## Publica contenido relevante\n## Interactúa con tu red', 'uploads/news-items/default.jpg', '14-como-usar-linkedin-de-forma-efectiva', '2025-04-05'),
  (15, 'Estrategias para encontrar empleo', 'Busca empleo de forma inteligente', '# Estrategias para encontrar empleo\n\n## Define tu objetivo\n## Usa LinkedIn\n## Prepara tu currículum', 'uploads/news-items/default.jpg', '15-estrategias-para-encontrar-empleo', '2025-04-12'),
  (16, 'Cómo mejorar tu marca personal', 'Refuerza tu presencia profesional', '# Cómo mejorar tu marca personal\n\n## Define tu nicho\n## Sé coherente\n## Crea contenido valioso', 'uploads/news-items/default.jpg', '16-como-mejorar-tu-marca-personal', '2025-04-19'),
  (17, 'Preparación para entrevistas de trabajo', 'Tips para destacar en tu entrevista', '# Preparación para entrevistas de trabajo\n\n## Investiga la empresa\n## Practica tus respuestas\n## Sé puntual', 'uploads/news-items/default.jpg', '17-preparacion-para-entrevistas-de-trabajo', '2025-04-26'),
  (18, 'Cómo escribir una carta de presentación efectiva', 'Guía para destacar con tu carta', '# Cómo escribir una carta de presentación efectiva\n\n## Investiga la empresa\n## Personaliza tu carta\n## Sé claro y directo', 'uploads/news-items/default.jpg', '18-como-escribir-una-carta-de-presentacion-efectiva', '2025-05-03'),
  (19, 'Habilidades blandas para el éxito profesional', 'Claves para destacar en tu carrera', '# Habilidades blandas para el éxito profesional\n\n## Comunicación\n## Colaboración\n## Resiliencia', 'uploads/news-items/default.jpg', '19-habilidades-blandas-para-el-exito-profesional', '2025-05-10'),
  (20, 'Cómo ser un buen líder sin ser jefe', 'Influye sin tener autoridad formal', '# Cómo ser un buen líder sin ser jefe\n\n## Liderazgo informal\n## Confianza\n## Ejemplo a seguir', 'uploads/news-items/default.jpg', '20-como-ser-un-buen-lider-sin-ser-jefe', '2025-05-17'),
  (21, 'Claves para el crecimiento profesional', 'Cómo avanzar en tu carrera', '# Claves para el crecimiento profesional\n\n## Aprendizaje continuo\n## Mentoría\n## Networking', 'uploads/news-items/default.jpg', '21-claves-para-el-crecimiento-profesional', '2025-05-24'),
  (22, 'Cómo manejar el estrés laboral', 'Herramientas para mejorar tu bienestar', '# Cómo manejar el estrés laboral\n\n## Técnicas de relajación\n## Manejo del tiempo\n## Límites claros', 'uploads/news-items/default.jpg', '22-como-manejar-el-estres-laboral', '2025-05-31'),
  (23, 'La importancia de la comunicación no verbal', 'Proyecta confianza y claridad', '# La importancia de la comunicación no verbal\n\n## Lenguaje corporal\n## Contacto visual\n## Tono de voz', 'uploads/news-items/default.jpg', '23-la-importancia-de-la-comunicacion-no-verbal', '2025-06-07'),
  (24, 'Cómo encontrar empleo en tiempos de crisis', 'Oportunidades en contextos difíciles', '# Cómo encontrar empleo en tiempos de crisis\n\n## Adaptabilidad\n## Redes de contacto\n## Formación continua', 'uploads/news-items/default.jpg', '24-como-encontrar-empleo-en-tiempos-de-crisis', '2025-06-14'),
  (25, 'Cómo desarrollar habilidades de negociación', 'Claves para acuerdos ganar-ganar', '# Cómo desarrollar habilidades de negociación\n\n## Escucha activa\n## Enfócate en intereses\n## Busca soluciones', 'uploads/news-items/default.jpg', '25-como-desarrollar-habilidades-de-negociacion', '2025-06-21'),
  (26, 'Cómo crear una red de contactos sólida', 'Construye relaciones profesionales reales', '# Cómo crear una red de contactos sólida\n\n## Sé útil\n## Sé constante\n## Sé auténtico', 'uploads/news-items/default.jpg', '26-como-crear-una-red-de-contactos-solida', '2025-06-28'),
  (27, 'La importancia de la retroalimentación', 'Cómo recibir y dar feedback', '# La importancia de la retroalimentación\n\n## Acepta con humildad\n## Sé claro y constructivo\n## Mejora con cada feedback', 'uploads/news-items/default.jpg', '27-la-importancia-de-la-retroalimentacion', '2025-07-05'),
  (28, 'Cómo escribir una recomendación de impacto', 'Claves para destacar en LinkedIn', '# Cómo escribir una recomendación de impacto\n\n## Sé específico\n## Muestra valor\n## Destaca logros', 'uploads/news-items/default.jpg', '28-como-escribir-una-recomendacion-de-impacto', '2025-07-12'),
  (29, 'Cómo escribir un post de LinkedIn exitoso', 'Consejos para aumentar tu visibilidad', '# Cómo escribir un post de LinkedIn exitoso\n\n## Sé claro\n## Usa ejemplos\n## Incluye llamadas a la acción', 'uploads/news-items/default.jpg', '29-como-escribir-un-post-de-linkedin-exitoso', '2025-07-18'),
  (30, 'Cómo conseguir prácticas profesionales', 'Consejos para jóvenes profesionales', '# Cómo conseguir prácticas profesionales\n\n## Crea un perfil sólido\n## Busca oportunidades activamente\n## Prepárate para la entrevista', 'uploads/news-items/default.jpg', '30-como-conseguir-practicas-profesionales', '2025-07-21');

-- migrate:down

TRUNCATE news_items;